apiVersion: v1
kind: Secret
metadata:
  name: nraa-enduro-secret
type: Opaque
stringData:
  nraa-enduro-worker.toml: |
    debug = true
    verbosity = 2

    [temporal]
    address = "temporal-frontend.enduro-sdps:7233"
    namespace = "default"

    [worker]
    taskQueue = "nraa-enduro"
    maxConcurrentSessions = 1

    [preprocessing]
    workflowName = "preprocessing"
    sharedPath = "/home/enduro/shared"

    [preprocessing.bagCreate]
    checksumAlgorithm = "sha512"

    [preprocessing.removeFiles]
    removeNames = ["thumbs.db", ".DS_Store"]

    [preprocessing.fileFormat]
    # Configure at most one of these paths.
    # allowlistPath = "/home/enduro/config/allowed-file-formats.csv"
    # disallowlistPath = "/home/enduro/config/disallowed-file-formats.csv"

    [preprocessing.fileValidate.veraPDF]
    # path = "/usr/bin/verapdf"
